[package]
name = "aoc-2025-day-10"
version = "0.1.0"
authors = ["Sebastian Ziebell <sebastian.ziebell@gmail.com"]
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
good_lp = { version = "1.14.2", features = ["microlp"], default-features = false }
itertools = "0.14"
nom = "8.0.0"
